source 'http://rubygems.org'

ruby '~> 2.5.0'

# This is a separate Gemfile because there's some clash of dependencies.

gem 'openstudio-common-measures', '~> 0.2.0'
gem 'openstudio-model-articulation', '~> 0.2.0'

gem 'urbanopt-geojson', '~> 0.4.0'
gem 'urbanopt-reporting', '~> 0.2.0'

gem 'openstudio-load-flexibility-measures', '~> 0.1.3'
